### ISSUE TITLE
Crash when no character is selected during login process and next is clicked

### ISSUE THREAD

**Issue by PatrikSamuelTauchim** [ZaneDubya/UltimaXNA#136]
When no character is selected from list during login process and next is clicked, crash happen.

System.IndexOutOfRangeException was unhandled
  HResult=-2146233080
  Message=Index was outside the bounds of the array.
  Source=UltimaXNA
  StackTrace:
       at UltimaXNA.Ultima.Login.LoginClient.LoginWithCharacter(Int32 index) in D:\UltimaXNA-master\dev\Ultima\Login\LoginClient.cs:line 184
       at UltimaXNA.Ultima.Login.States.CharacterListState.OnLoginWithCharacter(Int32 index) in D:\UltimaXNA-master\dev\Ultima\Login\States\CharacterListState.cs:line 103
       at UltimaXNA.Ultima.Login.Gumps.CharacterListGump.ActivateByButton(Int32 buttonID) in D:\UltimaXNA-master\dev\Ultima\Login\Gumps\CharacterListGump.cs:line 116
       at UltimaXNA.Ultima.UI.AControl.ActivateByButton(Int32 buttonID) in D:\UltimaXNA-master\dev\Ultima\UI\AControl.cs:line 377
       at UltimaXNA.Ultima.UI.Controls.Button.OnMouseClick(Int32 x, Int32 y, MouseButton button) in D:\UltimaXNA-master\dev\Ultima\UI\Controls\Button.cs:line 191
       at UltimaXNA.Ultima.UI.AControl.MouseClick(Point position, MouseButton button) in D:\UltimaXNA-master\dev\Ultima\UI\AControl.cs:line 580
       at UltimaXNA.Ultima.UI.UserInterfaceService.InternalHandleMouseInput() in D:\UltimaXNA-master\dev\Ultima\UI\UserInterfaceService.cs:line 399
       at UltimaXNA.Ultima.UI.UserInterfaceService.Update(Double totalMS, Double frameMS) in D:\UltimaXNA-master\dev\Ultima\UI\UserInterfaceService.cs:line 261
       at UltimaXNA.UltimaEngine.Update(GameTime gameTime) in D:\UltimaXNA-master\dev\UltimaEngine.cs:line 168
       at Microsoft.Xna.Framework.Game.Tick()
       at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
       at Microsoft.Xna.Framework.GameHost.OnIdle()
       at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
       at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
       at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
       at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.Run(Form mainForm)
       at Microsoft.Xna.Framework.WindowsGameHost.Run()
       at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
       at Microsoft.Xna.Framework.Game.Run()
       at UltimaXNA.Bootstrapper.StartEngine() in D:\UltimaXNA-master\dev\Bootstrapper.cs:line 147
       at UltimaXNA.Bootstrapper.Initialize() in D:\UltimaXNA-master\dev\Bootstrapper.cs:line 123
       at UltimaXNA.Bootstrapper.Main(String[] args) in D:\UltimaXNA-master\dev\Bootstrapper.cs:line 24
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by ZaneDubya** [comment]
Thanks @Eskymak . Should be easy to fix this. As a possible improvement, it would be great to indicate, in some fashion, that a character is selected...
