### ISSUE TITLE
Song playback failed

### ISSUE THREAD

**Issue by PatrikSamuelTauchim** [ZaneDubya/UltimaXNA#207]
**Song playback failed. Please verify that the song is not DRM protected. DRM protected songs are not supported for creator games.**

If there is no bug in code and it works for most of others, I guess that it could be caused by missing "multimedia features" in Windows (7/8/8.1) **N** editions. But no research (googleing) done on that.

```
   at Microsoft.Xna.Framework.Media.MediaQueue.Play(Song song)
   at Microsoft.Xna.Framework.Media.MediaPlayer.Play(Song song)
   at UltimaXNA.Ultima.Audio.AudioService.PlayMusic(Int32 id) in C:\Users\VM\Desktop\UltimaXNA-master\UltimaXNA-master\dev\Ultima\Audio\AudioService.cs:line 83
   at UltimaXNA.UltimaGame.Initialize() in C:\Users\VM\Desktop\UltimaXNA-master\UltimaXNA-master\dev\UltimaGame.cs:line 174
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Microsoft.Xna.Framework.Game.Run()
   at UltimaXNA.Bootstrapper.StartEngine() in C:\Users\VM\Desktop\UltimaXNA-master\UltimaXNA-master\dev\Bootstrapper.cs:line 83
   at UltimaXNA.Bootstrapper.Initialize() in C:\Users\VM\Desktop\UltimaXNA-master\UltimaXNA-master\dev\Bootstrapper.cs:line 66
   at UltimaXNA.Bootstrapper.Main(String[] args) in C:\Users\VM\Desktop\UltimaXNA-master\UltimaXNA-master\dev\Bootstrapper.cs:line 33
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by PatrikSamuelTauchim** [comment]
Duplicate of #203
