### ISSUE TITLE
OutOfRangeException

### ISSUE THREAD

**Issue by PatrikSamuelTauchim** [ZaneDubya/UltimaXNA#262]
Some specific NPC in range probably causing this, sometimes it crashes right on entering world in specific area, sometimes after some steps. 

```
System.IndexOutOfRangeException was unhandled
  HResult=-2146233080
  Message=Index was outside the bounds of the array.
  Source=UltimaXNA
  StackTrace:
       at UltimaXNA.Ultima.World.WorldClient.add_Item(Serial serial, Int32 itemID, Int32 nHue, Serial parentSerial, Int32 amount) in D:\GitHub\UltimaXNA\dev\Ultima\World\WorldClient.cs:line 335
       at UltimaXNA.Ultima.World.WorldClient.ReceiveAddMultipleItemsToContainer(IRecvPacket packet) in D:\GitHub\UltimaXNA\dev\Ultima\World\WorldClient.cs:line 291
       at UltimaXNA.Core.Network.NetworkClient.InvokeHandlers(List`1 packetHandlers, Byte[] buffer, Int32 length) in D:\GitHub\UltimaXNA\dev\Core\Network\NetworkClient.cs:line 533
       at UltimaXNA.Core.Network.NetworkClient.Slice() in D:\GitHub\UltimaXNA\dev\Core\Network\NetworkClient.cs:line 474
       at UltimaXNA.UltimaGame.Update(GameTime gameTime) in D:\GitHub\UltimaXNA\dev\UltimaGame.cs:line 205
       at Microsoft.Xna.Framework.Game.Tick()
       at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
       at Microsoft.Xna.Framework.GameHost.OnIdle()
       at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
       at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
       at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
       at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.Run(Form mainForm)
       at Microsoft.Xna.Framework.WindowsGameHost.Run()
       at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
       at Microsoft.Xna.Framework.Game.Run()
       at UltimaXNA.Bootstrapper.StartEngine() in D:\GitHub\UltimaXNA\dev\Bootstrapper.cs:line 79
       at UltimaXNA.Bootstrapper.Initialize() in D:\GitHub\UltimaXNA\dev\Bootstrapper.cs:line 62
       at UltimaXNA.Bootstrapper.Main(String[] args) in D:\GitHub\UltimaXNA\dev\Bootstrapper.cs:line 29
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

```

**Comment by ZaneDubya** [comment]
Hi @Eskymak - could you send me the files necessary to replicate this error? I would need your runuo directory and instructions as to what to do. Thanks!

**Comment by Eskymak** [comment]
@ZaneDubya 
I wanted to make it more simple for you, so I tryed to reproduce this on clean RunUO 2.5, but I am not even able to login... It is just keeps crashing on entering world. Original client works fine and only change that I made to RunUO was datapath to .mul files.

I also wiped whole world and still same
````
System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=UltimaXNA
  StackTrace:
       at UltimaXNA.Ultima.IO.AnimationData.GetAnimation(Int32 body, Int32 action, Int32 direction, Int32 hue) in D:\GitHub\UltimaXNA\dev\Ultima\IO\AnimationData.cs:line 75
       at UltimaXNA.Ultima.IO.AnimationData.GetAnimationFrameCount(Int32 body, Int32 action, Int32 direction, Int32 hue) in D:\GitHub\UltimaXNA\dev\Ultima\IO\AnimationData.cs:line 51
       at UltimaXNA.Ultima.World.EntityViews.MobileAnimation.animate(MobileAction action, Int32 actionIndex, Int32 repeatCount, Boolean reverse, Boolean repeat, Int32 delay, Boolean isRequestedAction) in D:\GitHub\UltimaXNA\dev\Ultima\World\EntityViews\MobileAnimation.cs:line 211
       at UltimaXNA.Ultima.World.EntityViews.MobileAnimation.Animate(MobileAction action) in D:\GitHub\UltimaXNA\dev\Ultima\World\EntityViews\MobileAnimation.cs:line 170
       at UltimaXNA.Ultima.World.EntityViews.MobileView.Draw(SpriteBatch3D spriteBatch, Vector3 drawPosition, MouseOverList mouseOverList, Map map) in D:\GitHub\UltimaXNA\dev\Ultima\World\EntityViews\MobileView.cs:line 58
       at UltimaXNA.Ultima.World.EntityViews.DeferredView.Draw(SpriteBatch3D spriteBatch, Vector3 drawPosition, MouseOverList mouseOverList, Map map) in D:\GitHub\UltimaXNA\dev\Ultima\World\EntityViews\DeferredView.cs:line 23
       at UltimaXNA.Ultima.World.WorldViews.IsometricRenderer.DrawEntities(Map map, Position3D center, MousePicking mousePicking, Vector2& renderOffset) in D:\GitHub\UltimaXNA\dev\Ultima\World\WorldViews\IsometricView.cs:line 200
       at UltimaXNA.Ultima.World.WorldViews.IsometricRenderer.Update(Map map, Position3D center, MousePicking mousePick) in D:\GitHub\UltimaXNA\dev\Ultima\World\WorldViews\IsometricView.cs:line 84
       at UltimaXNA.Ultima.World.WorldView.Draw(Double frameTime) in D:\GitHub\UltimaXNA\dev\Ultima\World\WorldView.cs:line 119
       at UltimaXNA.UltimaGame.Draw(GameTime gameTime) in D:\GitHub\UltimaXNA\dev\UltimaGame.cs:line 226
       at Microsoft.Xna.Framework.Game.DrawFrame()
       at Microsoft.Xna.Framework.Game.Tick()
       at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
       at Microsoft.Xna.Framework.GameHost.OnIdle()
       at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
       at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
       at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
       at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.Run(Form mainForm)
       at Microsoft.Xna.Framework.WindowsGameHost.Run()
       at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
       at Microsoft.Xna.Framework.Game.Run()
       at UltimaXNA.Bootstrapper.StartEngine() in D:\GitHub\UltimaXNA\dev\Bootstrapper.cs:line 79
       at UltimaXNA.Bootstrapper.Initialize() in D:\GitHub\UltimaXNA\dev\Bootstrapper.cs:line 62
       at UltimaXNA.Bootstrapper.Main(String[] args) in D:\GitHub\UltimaXNA\dev\Bootstrapper.cs:line 29
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
````

**Comment by PatrikSamuelTauchim** [comment]
@ZaneDubya OK, rgoing to test this on clean RunUO 2.5 to make it more simple

Ignore post before this that I removed, since this was caused by my "workaround" for one of those crashes. (i commented out crashing part)

**Comment by ZaneDubya** [comment]
Ok! I know what's causing this. The server is sending an item with an itemid > 0x4000. I wonder if the server is sending us an effect? Or perhaps an item that isn't included in the legacy client version I'm using?

The item ID that is sent is 0x7120. Is that used anywhere in the RunUO source code?

**Comment by ZaneDubya** [comment]
And 0x5d20, and dd20, and 0x5120, and 0x9920... hm... and more... always ending in 0x0020 though.

Serials for these items are 0x007fff91, 0x007fff90, 0x007fff8f, and continue counting down from there.

**Comment by PatrikSamuelTauchim** [comment]
@ZaneDubya Probably some effect or maybe animation? Corpses? Noticed this crash when few NPC were fighting, crashing in area. 

 0x7120 Is wall, 0x9920 is  part of flour mill

**Comment by PatrikSamuelTauchim** [comment]
@ZaneDubya I thing it just crashed when NPC died.

**Comment by PatrikSamuelTauchim** [comment]
@ZaneDubya  Just killed NPC with [KILL command => CRASH :-) After removing all corpses,  I was able to login in that area..

**Comment by ZaneDubya** [comment]
Hmm. I thought the item Id for corpses was 2006.

**Comment by PatrikSamuelTauchim** [comment]
It is...

**Comment by PatrikSamuelTauchim** [comment]
@ZaneDubya I guess that is has something to do with equiped items (or hairs?) on corpse. When I kill naked NPC  or dog, it is just fine and not crashing. When i remove items from corpse in classic client, I can also login after that

**Comment by PatrikSamuelTauchim** [comment]
Yep, removed spear from corpse and no crash anymore!

**Comment by ZaneDubya** [comment]
But why all the different item ids?! :)

**Comment by PatrikSamuelTauchim** [comment]
Dont know, maybe for all directions?

**Comment by ZaneDubya** [comment]
No, it's not a spear:

```
Format is serial, itemID, hue, containerID, amount
Baditemid: 0x007FFFC9 9520 8576 0x00004000 00
Baditemid: 0x007FFFC9 9120 8577 0x00004000 00
Baditemid: 0x007FFFC9 8d20 8578 0x00004000 00
Baditemid: 0x007FFFC9 8920 8579 0x00004000 00
```

Serial is repeated, itemid is decremented by 0x0400 each item, hue increases by 1, and parent serial is always 0x00004000. Bizarre.

**Comment by ZaneDubya** [comment]
More, from a few minutes later:
````
Baditemid: 0x007FFFAB 8120 0ac1 0x00004002 00
Baditemid: 0x007FFFAB 7d20 0ac2 0x00004002 00
Baditemid: 0x007FFFAB 4920 0ac3 0x00004002 00
Baditemid: 0x007FFFAA 8920 0ac5 0x00004002 00
Baditemid: 0x007FFFAA 8520 0ac6 0x00004002 00
Baditemid: 0x007FFFAA 7520 0ac7 0x00004002 00
Baditemid: 0x007FFFAA 7120 0ac8 0x00004002 00
Baditemid: 0x007FFFAA 6920 0ac9 0x00004002 00
Baditemid: 0x007FFFAA 4520 0aca 0x00004002 00
Baditemid: 0x007FFFA9 e920 0ad0 0x00004002 00
Baditemid: 0x007FFFA9 bd20 0ad1 0x00004002 00
Baditemid: 0x007FFFA9 9920 0ad2 0x00004002 00
Baditemid: 0x007FFFA9 7520 0ad3 0x00004002 00
Baditemid: 0x007FFFA9 6120 0ad4 0x00004002 00
Baditemid: 0x007FFFA8 f920 0ad7 0x00004002 00
Baditemid: 0x007FFFA8 f120 0ad8 0x00004002 00
Baditemid: 0x007FFFA8 e120 0ad9 0x00004002 00
Baditemid: 0x007FFFA8 dd20 0ada 0x00004002 00
Baditemid: 0x007FFFA8 a520 0adb 0x00004002 00
Baditemid: 0x007FFFA7 ed20 0ade 0x00004002 00
Baditemid: 0x007FFFA7 e120 0adf 0x00004002 00
Baditemid: 0x007FFFA7 b920 0ae0 0x00004002 00
Baditemid: 0x007FFFA7 ad20 0ae1 0x00004002 00
Baditemid: 0x007FFFA7 9120 0ae2 0x00004002 00
Baditemid: 0x007FFFA7 7d20 0ae3 0x00004002 00
Baditemid: 0x007FFFA7 6d20 0ae4 0x00004002 00
Baditemid: 0x007FFFA7 6520 0ae5 0x00004002 00
Baditemid: 0x007FFFA7 5120 0ae6 0x00004002 00
Baditemid: 0x007FFFA7 4d20 0ae7 0x00004002 00
Baditemid: 0x007FFFA7 4920 0ae8 0x00004002 00
Baditemid: 0x007FFFAC 7d20 0aec 0x00004002 00
Baditemid: 0x007FFFA9 d120 0aed 0x00004002 00
Baditemid: 0x007FFFA9 c520 0aee 0x00004002 00
Baditemid: 0x007FFFA9 c120 0aef 0x00004002 00
Baditemid: 0x007FFFA9 8d20 0af0 0x00004002 00
Baditemid: 0x007FFFA9 6920 0af1 0x00004002 00
Baditemid: 0x007FFFA8 ad20 0af4 0x00004002 00
Baditemid: 0x007FFFA8 4520 0af5 0x00004002 00
Baditemid: 0x007FFFA7 fd20 0af6 0x00004002 00
Baditemid: 0x007FFFA7 b520 0af7 0x00004002 00
Baditemid: 0x007FFFA7 9520 0af8 0x00004002 00
Baditemid: 0x007FFFA7 8d20 0af9 0x00004002 00
Baditemid: 0x007FFFA7 8520 0afa 0x00004002 00
Baditemid: 0x007FFFA7 7120 0afb 0x00004002 00
Baditemid: 0x007FFFA7 6120 0afc 0x00004002 00
Baditemid: 0x007FFFA9 8520 0b00 0x00004002 00
Baditemid: 0x007FFFA7 f120 0b01 0x00004002 00
Baditemid: 0x007FFFA7 6920 0b02 0x00004002 00
Baditemid: 0x007FFFA7 4520 0b03 0x00004002 00
Baditemid: 0x007FFFA9 dd20 0b07 0x00004002 00
Baditemid: 0x007FFFA7 7920 0b08 0x00004002 00
Baditemid: 0x007FFFA9 9520 0b0b 0x00004002 00
````

**Comment by ZaneDubya** [comment]
Aha, I found out what was going on! RunUO now expects the Client to always handle a revision to packet 0x3C (container contents) that was introduced in patch 6.0.1.7. When I started programming the xna client in 2009, this was not the case.

Fixed in 74daa9ca0c03d9fd0dbb23e9df840418d6fbed73 - and my fix will handle both old RunUO and new RunUO. :)

**Comment by PatrikSamuelTauchim** [comment]
Perfect, I noticed in client console (with packets enabled) that last packed from server before crash is this one!

**Comment by ZaneDubya** [comment]
Cool! Thanks for tracking this down!
