### ISSUE TITLE
System.NullReferenceException was unhandled

### ISSUE THREAD

**Issue by PatrikSamuelTauchim** [ZaneDubya/UltimaXNA#263]
I got disconnected by RunUO because of "Too much data pending" (There were hundreds of NPC in logout area) and after attempt to login I got this...

```
System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=UltimaXNA
  StackTrace:
       at UltimaXNA.Ultima.World.WorldClient.ReceiveObjectPropertyList(IRecvPacket packet) in D:\GitHub\UltimaXNA\dev\Ultima\World\WorldClient.cs:line 927
       at UltimaXNA.Core.Network.NetworkClient.InvokeHandlers(List`1 packetHandlers, Byte[] buffer, Int32 length) in D:\GitHub\UltimaXNA\dev\Core\Network\NetworkClient.cs:line 533
       at UltimaXNA.Core.Network.NetworkClient.Slice() in D:\GitHub\UltimaXNA\dev\Core\Network\NetworkClient.cs:line 474
       at UltimaXNA.UltimaGame.Update(GameTime gameTime) in D:\GitHub\UltimaXNA\dev\UltimaGame.cs:line 205
       at Microsoft.Xna.Framework.Game.Tick()
       at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
       at Microsoft.Xna.Framework.GameHost.OnIdle()
       at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
       at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
       at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
       at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.Run(Form mainForm)
       at Microsoft.Xna.Framework.WindowsGameHost.Run()
       at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
       at Microsoft.Xna.Framework.Game.Run()
       at UltimaXNA.Bootstrapper.StartEngine() in D:\GitHub\UltimaXNA\dev\Bootstrapper.cs:line 79
       at UltimaXNA.Bootstrapper.Initialize() in D:\GitHub\UltimaXNA\dev\Bootstrapper.cs:line 62
       at UltimaXNA.Bootstrapper.Main(String[] args) in D:\GitHub\UltimaXNA\dev\Bootstrapper.cs:line 29
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```

**Comment by ZaneDubya** [comment]
Hi @Eskymak, see my question in #262.

**Comment by PatrikSamuelTauchim** [comment]
@ZaneDubya Reproduced on clean RunUO 2.5
Steps to reproduce
- use command **[tilez 20 dummyfence**
- target right and then left side of the screen. This will spawn hundreds of NPC leading into "Too many data pending and disconnect"
- You will get Connecting lost and then you are at login screen
- Hit Next to login
- CRASH

**Comment by ZaneDubya** [comment]
Thanks @Eskymak. I was able to replicate the crash and I think I know how to fix it... Note that it is RunUO that is disconnecting us to begin with;

```
Client: 127.0.0.1: Too much data pending, disconnecting...
Client: 127.0.0.1: Disconnected. [0 Online] [Admin]
```

**Comment by ZaneDubya** [comment]
Ah, I see you already wrote that in your summary! haha

Ok, should be fixed! Thanks for reporting this bug!
