### ISSUE TITLE
Another System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by PatrikSamuelTauchim** [ZaneDubya/UltimaXNA#265]
Many NPCs from spawner were being killed by town guards and lightning, client was running for a while and then ended with this.

```
System.IndexOutOfRangeException was unhandled
  HResult=-2146233080
  Message=Index was outside the bounds of the array.
  Source=UltimaXNA
  StackTrace:
       at UltimaXNA.Ultima.IO.AnimationData.checkCache(Int32 body, Int32 action, Int32 direction) in D:\GitHub\UltimaXNA\dev\Ultima\IO\AnimationData.cs:line 145
       at UltimaXNA.Ultima.IO.AnimationData.GetAnimation(Int32 body, Int32 action, Int32 direction, Int32 hue) in D:\GitHub\UltimaXNA\dev\Ultima\IO\AnimationData.cs:line 66
       at UltimaXNA.Ultima.IO.AnimationData.GetAnimationFrameCount(Int32 body, Int32 action, Int32 direction, Int32 hue) in D:\GitHub\UltimaXNA\dev\Ultima\IO\AnimationData.cs:line 51
       at UltimaXNA.Ultima.World.EntityViews.MobileAnimation.animate(MobileAction action, Int32 actionIndex, Int32 repeatCount, Boolean reverse, Boolean repeat, Int32 delay, Boolean isRequestedAction) in D:\GitHub\UltimaXNA\dev\Ultima\World\EntityViews\MobileAnimation.cs:line 211
       at UltimaXNA.Ultima.World.EntityViews.MobileAnimation.Animate(MobileAction action) in D:\GitHub\UltimaXNA\dev\Ultima\World\EntityViews\MobileAnimation.cs:line 170
       at UltimaXNA.Ultima.World.EntityViews.MobileView.Draw(SpriteBatch3D spriteBatch, Vector3 drawPosition, MouseOverList mouseOverList, Map map) in D:\GitHub\UltimaXNA\dev\Ultima\World\EntityViews\MobileView.cs:line 58
       at UltimaXNA.Ultima.World.EntityViews.DeferredView.Draw(SpriteBatch3D spriteBatch, Vector3 drawPosition, MouseOverList mouseOverList, Map map) in D:\GitHub\UltimaXNA\dev\Ultima\World\EntityViews\DeferredView.cs:line 23
       at UltimaXNA.Ultima.World.WorldViews.IsometricRenderer.DrawEntities(Map map, Position3D center, MousePicking mousePicking, Vector2& renderOffset) in D:\GitHub\UltimaXNA\dev\Ultima\World\WorldViews\IsometricView.cs:line 200
       at UltimaXNA.Ultima.World.WorldViews.IsometricRenderer.Update(Map map, Position3D center, MousePicking mousePick) in D:\GitHub\UltimaXNA\dev\Ultima\World\WorldViews\IsometricView.cs:line 84
       at UltimaXNA.Ultima.World.WorldView.Draw(Double frameTime) in D:\GitHub\UltimaXNA\dev\Ultima\World\WorldView.cs:line 119
       at UltimaXNA.UltimaGame.Draw(GameTime gameTime) in D:\GitHub\UltimaXNA\dev\UltimaGame.cs:line 226
       at Microsoft.Xna.Framework.Game.DrawFrame()
       at Microsoft.Xna.Framework.Game.Tick()
       at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
       at Microsoft.Xna.Framework.GameHost.OnIdle()
       at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
       at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
       at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
       at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.Run(Form mainForm)
       at Microsoft.Xna.Framework.WindowsGameHost.Run()
       at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
       at Microsoft.Xna.Framework.Game.Run()
       at UltimaXNA.Bootstrapper.StartEngine() in D:\GitHub\UltimaXNA\dev\Bootstrapper.cs:line 79
       at UltimaXNA.Bootstrapper.Initialize() in D:\GitHub\UltimaXNA\dev\Bootstrapper.cs:line 62
       at UltimaXNA.Bootstrapper.Main(String[] args) in D:\GitHub\UltimaXNA\dev\Bootstrapper.cs:line 29
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```

**Comment by ZaneDubya** [comment]
Hi @Eskymak, see my question in #262.

**Comment by PatrikSamuelTauchim** [comment]
@ZaneDubya  Reproduced in clean runuo 2.5
- Follow steps on #263
- You wont be able to login at place where you spawned those NPCs until they die (they are killed automatically by timer in 5 minutes)
- UltimaXNA also crashed, when I used **[SET MAP 0** on myself, so I ended in that area

Probably related to too many NPCs

**Comment by ZaneDubya** [comment]
Can you debug it when it crashes and see what bodyID is being referenced by UltimaXNA.Ultima.IO.AnimationData.checkCache? I had this error happen as well, and the BodyID was zero.

**Comment by PatrikSamuelTauchim** [comment]
Sure, just tell me where to find this :-)

**Comment by ZaneDubya** [comment]
Just follow the stack trace when it crashes :) When I'm debugging, I try to find out the first object with 'bad' data, and then figure out why it's in error.

**Comment by PatrikSamuelTauchim** [comment]
Uhm, where? If in VS, there is so many numbers and information I can provide, but if you want just one, you need to be more specific :-/

**Comment by PatrikSamuelTauchim** [comment]
Could it be this? Parameter values were disable by default :-/

```
>   UltimaXNA.exe!UltimaXNA.Ultima.Resources.AnimationResource.CheckCache(int body = 0, int action = -1, int direction = 0) Line 140 + 0x24 bytes   C#`
```

**Comment by ZaneDubya** [comment]
@Eskymak Can you still replicate this crash? I believe I've added a lot of error checking in the past week and this error might now be handled. Thank you!

**Comment by PatrikSamuelTauchim** [comment]
@ZaneDubya Nope, but got #269 instead :-D

**Comment by ZaneDubya** [comment]
@Eskymak :(

**Comment by ZaneDubya** [comment]
Ok, closing as fixed.
