### ISSUE TITLE
Lightning effect does (sometimes) IndexOutOfRangeException

### ISSUE THREAD

**Issue by PatrikSamuelTauchim** [ZaneDubya/UltimaXNA#269]
Found this one while working on #265 I guess, this one should be easy! :-)
- Go to Britain center, where guards are (they will spawn when someone call them) 
- [tilez 25 dummysuper
- lightning show will start once they will call guards
- spawn more if needed
- Eventually it will crash on one of those lightnings. It can run minutes with tens of lightnings on the same time or crash after few seconds

```
System.IndexOutOfRangeException was unhandled
  HResult=-2146233080
  Message=Index was outside the bounds of the array.
  Source=UltimaXNA
  StackTrace:
       at UltimaXNA.Ultima.World.EntityViews.LightningEffectView.Draw(SpriteBatch3D spriteBatch, Vector3 drawPosition, MouseOverList mouseOverList, Map map) in C:\Users\VM\Desktop\UltimaXNA-master\dev\Ultima\World\EntityViews\LightningEffectView.cs:line 50
       at UltimaXNA.Ultima.World.EntityViews.DeferredView.Draw(SpriteBatch3D spriteBatch, Vector3 drawPosition, MouseOverList mouseOverList, Map map) in C:\Users\VM\Desktop\UltimaXNA-master\dev\Ultima\World\EntityViews\DeferredView.cs:line 23
       at UltimaXNA.Ultima.World.WorldViews.IsometricRenderer.DrawEntities(Map map, Position3D center, MousePicking mousePicking, Vector2& renderOffset) in C:\Users\VM\Desktop\UltimaXNA-master\dev\Ultima\World\WorldViews\IsometricView.cs:line 200
       at UltimaXNA.Ultima.World.WorldViews.IsometricRenderer.Update(Map map, Position3D center, MousePicking mousePick) in C:\Users\VM\Desktop\UltimaXNA-master\dev\Ultima\World\WorldViews\IsometricView.cs:line 84
       at UltimaXNA.Ultima.World.WorldView.Draw(Double frameTime) in C:\Users\VM\Desktop\UltimaXNA-master\dev\Ultima\World\WorldView.cs:line 119
       at UltimaXNA.UltimaGame.Draw(GameTime gameTime) in C:\Users\VM\Desktop\UltimaXNA-master\dev\UltimaGame.cs:line 224
       at Microsoft.Xna.Framework.Game.DrawFrame()
       at Microsoft.Xna.Framework.Game.Tick()
       at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
       at Microsoft.Xna.Framework.GameHost.OnIdle()
       at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
       at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
       at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
       at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.Run(Form mainForm)
       at Microsoft.Xna.Framework.WindowsGameHost.Run()
       at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
       at Microsoft.Xna.Framework.Game.Run()
       at UltimaXNA.Bootstrapper.StartEngine() in C:\Users\VM\Desktop\UltimaXNA-master\dev\Bootstrapper.cs:line 79
       at UltimaXNA.Bootstrapper.Initialize() in C:\Users\VM\Desktop\UltimaXNA-master\dev\Bootstrapper.cs:line 62
       at UltimaXNA.Bootstrapper.Main(String[] args) in C:\Users\VM\Desktop\UltimaXNA-master\dev\Bootstrapper.cs:line 29
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```

**Comment by ZaneDubya** [comment]
@Eskymak I am no longer getting this error, and I think I've fixed this. Please let me know if you can reproduce it.

**Comment by PatrikSamuelTauchim** [comment]
@ZaneDubya I was not able to crash it, looks fixed. Thanks!

**Comment by ZaneDubya** [comment]
Thanks @Eskymak!

**Comment by PatrikSamuelTauchim** [comment]
@ZaneDubya Sorry, crashed again with current master. :-(

```
System.IndexOutOfRangeException was unhandled
  HResult=-2146233080
  Message=Index was outside the bounds of the array.
  Source=UltimaXNA
  StackTrace:
       at UltimaXNA.Ultima.World.EntityViews.LightningEffectView.Draw(SpriteBatch3D spriteBatch, Vector3 drawPosition, MouseOverList mouseOverList, Map map) in C:\Users\VM\Desktop\UltimaXNA-master\dev\Ultima\World\EntityViews\LightningEffectView.cs:line 50
       at UltimaXNA.Ultima.World.EntityViews.DeferredView.Draw(SpriteBatch3D spriteBatch, Vector3 drawPosition, MouseOverList mouseOverList, Map map) in C:\Users\VM\Desktop\UltimaXNA-master\dev\Ultima\World\EntityViews\DeferredView.cs:line 32
       at UltimaXNA.Ultima.World.WorldViews.IsometricRenderer.DrawEntities(Map map, Position3D center, MousePicking mousePicking, Vector2& renderOffset) in C:\Users\VM\Desktop\UltimaXNA-master\dev\Ultima\World\WorldViews\IsometricView.cs:line 202
       at UltimaXNA.Ultima.World.WorldViews.IsometricRenderer.Update(Map map, Position3D center, MousePicking mousePick) in C:\Users\VM\Desktop\UltimaXNA-master\dev\Ultima\World\WorldViews\IsometricView.cs:line 85
       at UltimaXNA.Ultima.World.WorldView.Draw(Double frameTime) in C:\Users\VM\Desktop\UltimaXNA-master\dev\Ultima\World\WorldView.cs:line 122
       at UltimaXNA.UltimaGame.Draw(GameTime gameTime) in C:\Users\VM\Desktop\UltimaXNA-master\dev\UltimaGame.cs:line 225
       at Microsoft.Xna.Framework.Game.DrawFrame()
       at Microsoft.Xna.Framework.Game.Tick()
       at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
       at Microsoft.Xna.Framework.GameHost.OnIdle()
       at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
       at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
       at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
       at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.Run(Form mainForm)
       at Microsoft.Xna.Framework.WindowsGameHost.Run()
       at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
       at Microsoft.Xna.Framework.Game.Run()
       at UltimaXNA.Bootstrapper.StartEngine() in C:\Users\VM\Desktop\UltimaXNA-master\dev\Bootstrapper.cs:line 79
       at UltimaXNA.Bootstrapper.Initialize() in C:\Users\VM\Desktop\UltimaXNA-master\dev\Bootstrapper.cs:line 62
       at UltimaXNA.Bootstrapper.Main(String[] args) in C:\Users\VM\Desktop\UltimaXNA-master\dev\Bootstrapper.cs:line 29
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

```

```
>   UltimaXNA.exe!UltimaXNA.Ultima.World.EntityViews.LightningEffectView.Draw(UltimaXNA.Core.Graphics.SpriteBatch3D spriteBatch = {UltimaXNA.Core.Graphics.SpriteBatch3D}, Microsoft.Xna.Framework.Vector3 drawPosition = {Microsoft.Xna.Framework.Vector3}, UltimaXNA.Ultima.World.Input.MouseOverList mouseOverList = {UltimaXNA.Ultima.World.Input.MouseOverList}, UltimaXNA.Ultima.World.Maps.Map map = {UltimaXNA.Ultima.World.Maps.Map}) Line 50 + 0x1e bytes C#

```

**Comment by ZaneDubya** [comment]
Ok @Eskymak, I'm 99.99% certain I have it fixed now. Just try and reopen this one. I dare ya. ;)
