### ISSUE TITLE
[go doom causes a crash.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#279]
Info 2015-08-14 16:06:56:7974 System.IO.IOException: No process is on the other end of the pipe.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__ConsoleStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count)
   at System.IO.TextWriter.WriteLine(String value)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String value)
   at System.Console.WriteLine(String value)
   at UltimaXNA.Core.Diagnostics.Listeners.ConsoleOutputEventListener.OnEventWritten(EventLevels level, String message) in c:\Users\zanewagner\Desktop\UltimaXNA\dev\Core\Diagnostics\Listeners\ConsoleOutputEventListener.cs:line 42
   at UltimaXNA.Core.Diagnostics.Listeners.AEventListener.OnEventWritten(EventLevels level, String message, Object[] args)
   at UltimaXNA.Core.Diagnostics.Tracing.Tracer.Warn(String message, Object[] args)
   at UltimaXNA.Core.Network.NetworkClient.OnReceive(IAsyncResult result)
Info 2015-08-14 16:06:56:8004 Disconnected.

**Comment by ZaneDubya** [comment]
This might have something to do with where the doom dungeon is located on the map...

**Comment by ZaneDubya** [comment]
Nope, legacy client loads it fine. Hmmm.

**Comment by ZaneDubya** [comment]
This has to do with attempting to load map patches from dif files that do not exist. Fixed.
